### ISSUE TITLE
Handle big request more gracefully

### ISSUE THREAD

**Issue by mal-tee** [spq/pkappa2#48]
Firefox asked me to kill a tab when inspecting a bigger payload (2kb iirc)

**Comment by peace-maker** [comment]
I suspect this is rendering performance of the <span> around every byte for searching selections @schmop ?

**Comment by schmop** [comment]
When the massive usage of <span> tags around every char in the stream results in oom, then the "load more" option will only defer it until you loaded the whole stream.
Maybe we need to redesign the "copy/search from stream data" functionality. Or worst case remove it


Nonetheless, pagination would be awesome. Infinite scroll even?

**Comment by peace-maker** [comment]
We could show a warning banner for streams larger X instead of the contents like "This is a large stream, do you want to render it?" which would help skipping through results without getting stuck on those large streams.

This wouldn't fix the original issue, but make it a more concious decision to view the large stream. It's probably better to download the pcap and view it locally for >MB streams.
